spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.101.111:1521:orcl
    username: RDL_1023
    password: 1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      initial-size: 50
      max-active: 500
      min-idle: 20
      # 配置获取连接等待超时的时间
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      keep-alive: true